#!/bin/sh 

local TXSPEEDTHRELD=15000
local RXSPEEDTHRELD=15000
local test_seconds=30
local AUTO_UPDATE_MOD_ID=250
local LOG_INF_SKIP_UPGRADE=21
. /lib/functions.sh

debug_printf()
{
	echo "[auto_upgrade] $*" > /dev/console
}


wan_speed_busy()
{
	local rx_old_lo rx_old_hi tx_old_lo tx_old_hi rx_old_bytes tx_old_bytes
	local rx_new_lo rx_new_hi tx_new_lo tx_new_hi rx_new_bytes tx_new_bytes
	local rx_speed tx_speed rx_pkt tx_pkt
	local wan_unit wan_port wan_sec
	config_load switch
	config_get wan_sec wan switch_port "lan4wan"
	config_get wan_unit $wan_sec unit 0
	config_get wan_port $wan_sec port 1

	dmesg -c  >/dev/null 2>&1
	ethswctl -c mibdump -n $wan_unit -p $wan_port -a
	rx_old_lo=$(dmesg |grep RxOctetsLo |cut -d : -f 2-)
	rx_old_hi=$(dmesg |grep RxOctetsHi |cut -d : -f 2-)
	tx_old_lo=$(dmesg |grep TxOctetsLo |cut -d : -f 2-)
	tx_old_hi=$(dmesg |grep TxOctetsHi |cut -d : -f 2-)
	rx_old_bytes=$(dmesg |grep RxBytes |cut -d : -f 2-)
	tx_old_bytes=$(dmesg |grep TxBytes |cut -d : -f 2-)
	sleep $test_seconds
	dmesg -c  >/dev/null 2>&1
	ethswctl -c mibdump -n $wan_unit -p $wan_port -a
	rx_new_lo=$(dmesg |grep RxOctetsLo |cut -d : -f 2-)
	rx_new_hi=$(dmesg |grep RxOctetsHi |cut -d : -f 2-)
	tx_new_lo=$(dmesg |grep TxOctetsLo |cut -d : -f 2-)
	tx_new_hi=$(dmesg |grep TxOctetsHi |cut -d : -f 2-)
	rx_new_bytes=$(dmesg |grep RxBytes |cut -d : -f 2-)
	tx_new_bytes=$(dmesg |grep TxBytes |cut -d : -f 2-)

	if [ -z "$rx_old_lo" -a -z "$tx_old_lo" -a -z "$rx_new_lo" -a -z "$tx_new_lo" ];then
		rx_pkt=$((rx_new_bytes - rx_old_bytes))
		tx_pkt=$((tx_new_bytes - tx_old_bytes))
	else
		## when mib statistics hi 32bit is not the same ,we treat as wan busy
		[ "$rx_old_hi" != "$rx_new_hi" -o "$tx_old_hi" != "$tx_new_hi" ] && return 0

		rx_pkt=$((rx_new_lo - rx_old_lo))
		tx_pkt=$((tx_new_lo - tx_old_lo))
	fi
	rx_speed=$((rx_pkt/test_seconds))
	tx_speed=$((tx_pkt/test_seconds))
	debug_printf "rxSpeed = $rx_speed, txSpeed = $tx_speed"

	if [ $rx_speed -gt $RXSPEEDTHRELD  -o $tx_speed -gt $TXSPEEDTHRELD ];then
		return 0
	else
		return 1
	fi

}

wan_speed_busy_by_tfstats()
{
	local rx_old tx_old
	local rx_new tx_new
	local res_old res_new
	local rx_pkt tx_pkt rx_speed tx_speed

	res_old=$(get_rxtx_total_bytes)
	eval $(echo $res_old | awk '{gsub("rx_total_bytes", "rx_old");gsub("tx_total_bytes","tx_old");print $1}')

	sleep $test_seconds

	res_new=$(get_rxtx_total_bytes)
	eval $(echo $res_new | awk '{gsub("rx_total_bytes", "rx_new");gsub("tx_total_bytes","tx_new");print $1}')

	rx_pkt=$((rx_new - rx_old))
	tx_pkt=$((tx_new - tx_old))

	rx_speed=$((rx_pkt/test_seconds))
	tx_speed=$((tx_pkt/test_seconds))
	debug_printf "rxSpeed = $rx_speed, txSpeed = $tx_speed"

	if [ $rx_speed -gt $RXSPEEDTHRELD  -o $tx_speed -gt $TXSPEEDTHRELD ];then
	return 0
	else
	return 1
	fi
}

wan_speed_busy_is_ap_model()
{
	local rx_old tx_old
	local rx_new tx_new
	local res_old res_new
	local rx_pkt tx_pkt rx_speed tx_speed

	local sysmode
	config_load "sysmode"
	config_get sysmode sysmode mode

	if [ "$sysmode" == "ap" -o "$sysmode" == "multissid" ]; then
		rx_old=$(ifconfig eth1 | grep bytes | awk '{print $2}' | awk -F : '{print $2}')
		tx_old=$(ifconfig eth1 | grep bytes | awk '{print $6}' | awk -F : '{print $2}')

		sleep $test_seconds

		rx_new=$(ifconfig eth1 | grep bytes | awk '{print $2}' | awk -F : '{print $2}')
		tx_new=$(ifconfig eth1 | grep bytes | awk '{print $6}' | awk -F : '{print $2}')

	elif [ "$sysmode" == "repeater" -o "$sysmode" == "client" ]; then
		local sta_2g=`uci get profile.@wireless[0].wireless_sta_2g -c "/etc/profile.d"`
		local sta_5g=`uci get profile.@wireless[0].wireless_sta_5g -c "/etc/profile.d"`

		config_load "wireless"
		config_get enable_2g_old $sta_2g enable
		config_get enable_5g_old $sta_5g enable

		rx_old=0
		tx_old=0
		rx_new=0
		tx_new=0
		local rx_2g_old=0
		local rx_5g_old=0
		local tx_2g_old=0
		local tx_5g_old=0
		if [ "$enable_2g_old" == "on" ];then
			rx_2g_old=$(ifconfig $sta_2g | grep bytes | awk '{print $2}' | awk -F : '{print $2}')
			tx_2g_old=$(ifconfig $sta_2g | grep bytes | awk '{print $6}' | awk -F : '{print $2}')
			rx_old=$(($rx_old + $rx_2g_old))
			tx_old=$(($tx_old + $tx_2g_old))
		fi
		if [ "$enable_5g_old" == "on" ];then
			rx_5g_old=$(ifconfig $sta_5g | grep bytes | awk '{print $2}' | awk -F : '{print $2}')
			tx_5g_old=$(ifconfig $sta_5g | grep bytes | awk '{print $6}' | awk -F : '{print $2}')
			rx_old=$(($rx_old + $rx_5g_old))
			tx_old=$(($tx_old + $tx_5g_old))
		fi

		sleep $test_seconds

		config_load "wireless"
		config_get enable_2g_new $sta_2g enable
		config_get enable_5g_new $sta_5g enable
		if [ "$enable_2g_old" == "on" -a "$enable_2g_new" == "on" ];then
			rx_new=$(($rx_new + $(ifconfig $sta_2g | grep bytes | awk '{print $2}' | awk -F : '{print $2}')))
			tx_new=$(($tx_new + $(ifconfig $sta_2g | grep bytes | awk '{print $6}' | awk -F : '{print $2}')))
		else
			rx_new=$(($rx_new + $rx_2g_old))
			tx_new=$(($tx_new + $tx_2g_old))
		fi
		if [ "$enable_5g_old" == "on" -a "$enable_5g_new" == "on" ];then
			rx_new=$(($rx_new + $(ifconfig $sta_5g | grep bytes | awk '{print $2}' | awk -F : '{print $2}')))
			tx_new=$(($tx_new + $(ifconfig $sta_5g | grep bytes | awk '{print $6}' | awk -F : '{print $2}')))
		else
			rx_new=$(($rx_new + $rx_5g_old))
			tx_new=$(($tx_new + $tx_5g_old))
		fi
	fi

	rx_pkt=$((rx_new - rx_old))
	tx_pkt=$((tx_new - tx_old))

	rx_speed=$((rx_pkt/test_seconds))
	tx_speed=$((tx_pkt/test_seconds))
	debug_printf "rxSpeed = $rx_speed, txSpeed = $tx_speed"

	if [ $rx_speed -gt $RXSPEEDTHRELD  -o $tx_speed -gt $TXSPEEDTHRELD ];then
	return 0
	else
	return 1
	fi
}

wan_speed_busy_for_mtk798x()
{
	local rx_old_bytes tx_old_bytes
	local rx_new_bytes tx_new_bytes
	local rx_speed tx_speed rx_pkt tx_pkt
	
	local wan_sec=$(uci get switch.wan.switch_port)
	local wan_ifname=$(uci get switch.${wan_sec}.ifname)
	
	rx_old_bytes=$(ifconfig ${wan_ifname} | grep "RX bytes" | awk -F 'RX bytes:' '{print $2}' | awk -F ' ' '{print $1}')
	tx_old_bytes=$(ifconfig ${wan_ifname} | grep "TX bytes" | awk -F 'TX bytes:' '{print $2}' | awk -F ' ' '{print $1}')
	sleep $test_seconds
	rx_new_bytes=$(ifconfig ${wan_ifname} | grep "RX bytes" | awk -F 'RX bytes:' '{print $2}' | awk -F ' ' '{print $1}')
	tx_new_bytes=$(ifconfig ${wan_ifname} | grep "TX bytes" | awk -F 'TX bytes:' '{print $2}' | awk -F ' ' '{print $1}')
	
	rx_pkt=$((rx_new_bytes - rx_old_bytes))
	tx_pkt=$((tx_new_bytes - tx_old_bytes))
	
	rx_speed=$((rx_pkt/test_seconds))
	tx_speed=$((tx_pkt/test_seconds))
	debug_printf "rxSpeed = $rx_speed, txSpeed = $tx_speed"

	if [ $rx_speed -gt $RXSPEEDTHRELD -o $tx_speed -gt $TXSPEEDTHRELD ];then
		return 0
	else
		return 1
	fi
}

upgrade_ready()
{

	config_load cloud_config
	config_get fw_new_notify new_firmware fw_new_notify "0"
	config_load auto_upgrade
	config_get cloud_push upgrade cloud_push "0"
	if [ "$fw_new_notify" != "1" -o "$cloud_push" = "0" ];
	then
		debug_printf "no firmware to upgrade"
		return 1
	fi

	online-test
	if [ "$?" -ne 0 ];then
		debug_printf "online-test fail"
		return 1
	fi

	local model=$(uci get profile.@global[0].model -c "/etc/profile.d")
	local is_ap_model=`uci get profile.@global[0].is_ap_model -c "/etc/profile.d" -q`
	if [ "$is_ap_model" = "yes" ]; then
		wan_speed_busy_is_ap_model
	elif [ "$model" = "QCA_IPQ50XX" -o "$model" = "QCA_IPQ95XX" ];then
		wan_speed_busy_by_tfstats
	elif [ "$model" = "MTK_798x" ];then
		wan_speed_busy_for_mtk798x
	else
	wan_speed_busy 
	fi

	if [ "$?" -eq 0 ];then
		debug_printf "clients are surfing internet, delay auto upgrade!"
		delayCount=$(uci get auto_upgrade.upgrade.delay)
		logx -p $$ $AUTO_UPDATE_MOD_ID $LOG_INF_SKIP_UPGRADE
		if [ $delayCount -lt 10 ];then	
			debug_printf "set upgrade.delay = $((delayCount+1)) "
			uci set auto_upgrade.upgrade.delay=$((delayCount+1))
			uci commit auto_upgrade
			uci_commit_flash
		fi
		return 1
	fi
	return 0
}

SYS_SET_TIME=$(uci_get_state systime core sync)
type=$(uci get -q system.ntp.type)
[ $SYS_SET_TIME -eq 0 -o "$type" != "auto" ] && exit 0

upgrade_ready
if [ "$?" -eq 0 ];then
	
	touch /tmp/auto_update_lock.lua
	sleep 5

	# kickoff web
	rm -rf /tmp/luci-sessions/*

    [ -f "/tmp/applogin_flag" ] && {
		lua -e "require('luci.controller.login').kickoff_app()"
		rm -f /tmp/applogin_flag
	}

	/usr/sbin/cloud_upgrade

fi

rm -f /tmp/auto_update_lock.lua
