#!/bin/sh

check_lan_conn()
{	
	local res=$(sed -n '1p' /proc/driver/rtl8367s/phy)
	local count=0
	for port in ${res}
	do
			[ $count -eq 0 ] && {
				count=$(($count+1))
				continue
			}
			if [ $port -eq 1 ]; then
				return 0
			fi
			count=$(($count+1))
	done

	echo "lan not connected"
	return 1
}

check_lan_conn
return $?
