#!/usr/bin/lua
--created by wanghao

local error = require "cloud_report.report_error"
local sys   = require "luci.sys"
local nixio = require "nixio"
local dbg   = require "luci.tools.debug"
local json = require "luci.json"
local io    = require "io"
local uci			= require "luci.model.uci"
local uci_r			= uci.cursor()

local content_type = "Content-type: application/json"
local url_postfix = "/v1/messages/white-list"
local CLOUD_HOMECARE_TOKEN_FILE = "/tmp/cloud/cloud_token_homecare"
local CAT_RESULT = "/var/log/cloud_report_url_apply.cat"

local retry_count = 0
local token
local origin_url
local fp
local retry = false

if arg[1] == nil then
	dbg.print("must specify a profileid!")
	return false, "must specify a profileid!"
end

if arg[2] == nil then
	dbg.print("must specify a url!")
	return false, "must specify a url!"
end

while(retry_count <= 2)
do
	retry_count = retry_count + 1
	retry = false

	if not nixio.fs.access(CLOUD_HOMECARE_TOKEN_FILE) then
		sys.call("cloud_getDevToken homecare")
	end

	if nixio.fs.access(CLOUD_HOMECARE_TOKEN_FILE) then
		fp = io.open(CLOUD_HOMECARE_TOKEN_FILE, "r")
		token = fp:read("*line")
		origin_url = fp:read("*line")..url_postfix
		fp:close()
	else
		-- try again when not get the homecare token
		sys.call("cloud_getDevToken homecare")
		if nixio.fs.access(CLOUD_HOMECARE_TOKEN_FILE) then
			fp = io.open(CLOUD_HOMECARE_TOKEN_FILE, "r")
			token = fp:read("*line")
			origin_url = fp:read("*line") .. url_postfix
			fp:close()
		else		
			break
		end
	end
	
	local profileid = arg[1]
	local url = arg[2]
	local cat = "other"
	local content = ""
	sys.call("rm " .. CAT_RESULT)
	sys.call("export LD_LIBRARY_PATH=/usr/lib/avira:$LD_LIBRARY_PATH;/usr/bin/avira/libauc/libauc_1.0.0-1/auc_example -d '%s'"  % {url})
	if nixio.fs.access(CAT_RESULT) then
		fp = io.open(CAT_RESULT, "r")
		content = fp:read("*line")
		content = string.lower(content)
		fp:close()
		if string.find(content, "adult") then
			cat = "adult_content"
		elseif string.find(content, "gambling") then
			cat = "gambling"
		elseif string.find(content, "sex") then
			cat = "sex_education"
		elseif string.find(content, "communication") then
			cat = "online_communications"
		elseif string.find(content, "social") then
			cat = "social_network"
		elseif string.find(content, "pay") then
			cat = "pay_to_surf"
		elseif string.find(content, "media") then
			cat = "media"
		elseif string.find(content, "download") then
			cat = "download"
		elseif string.find(content, "game") then
			cat = "games"
		elseif string.find(content, "web") then
			cat = "web_search"
		end
	end
	
	local profilename = uci_r:get("parental_control_v2", profileid, "name") or ""
	local data = {
		["profileId"] = profileid,
		["profileName"] = profilename,
		["website"] = url,
		["type"] = cat,
		["deviceId"] = string.match(sys.exec("getfirm DEV_ID"), "%w+")	
	}
	
	sys.call("echo `date` >/var/log/cloud_report_url_apply.result; echo '%s' >>/var/log/cloud_report_url_apply.result" % {json.encode(data)})
	dbg.print("[cloud-report][" .. arg[0] .. "][cloud_upload request]:", json.encode(data))
	
	local ret
	fp = io.popen("curl --tlsv1.2 -S -l -H \"%s\" -H \"Authorization: %s\" -X POST -k -d \'%s\' --connect-timeout 8 %s --retry 3 --retry-delay 1 2>>/var/log/cloud_report_url_apply.result" % {content_type, token, json.encode(data), origin_url})
	if fp then
		ret = fp:read("*all")
		fp:close()
	end

	dbg.print("[cloud-report][" .. arg[0] .. "][cloud_upload response]:", ret)
	ret = json.decode(ret)

	if ret ~= nil then
		if tonumber(ret.code) == error.ERROR_MSG.ERROR_INVALID_DEVICE_TOKEN[1] then
			--refresh token and upload again
			sys.call("rm " .. CLOUD_HOMECARE_TOKEN_FILE)
			retry = true
		end
	end
	
	if retry == false then
		break
	end
	
end
