#!/usr/bin/lua

local error = require "cloud_report.report_error"
local sys   = require "luci.sys"
local nixio = require "nixio"
local dbg   = require "luci.tools.debug"
local json = require "luci.json"
local io    = require "io"

local content_type = "Content-type: application/json"
local url_postfix = "/v1/services/insights-upload"
local CLOUD_HOMECARE_TOKEN_FILE = "/tmp/cloud/cloud_token_homecare"
local CACERT_FILE = "/etc/certificate/2048_newroot.cer"

local retry_count = 0
local token
local origin_url
local fp
local retry = false

while(retry_count <= 2)
do
	retry_count = retry_count + 1
	retry = false

	if not nixio.fs.access(CLOUD_HOMECARE_TOKEN_FILE) then
		sys.call("cloud_getDevToken homecare")
	end

	if nixio.fs.access(CLOUD_HOMECARE_TOKEN_FILE) then
		fp = io.open(CLOUD_HOMECARE_TOKEN_FILE, "r")
		token = fp:read("*line")
		origin_url = fp:read("*line")..url_postfix
		fp:close()
	else
		-- try again when not get the homecare token
		sys.call("cloud_getDevToken homecare")
		if nixio.fs.access(CLOUD_HOMECARE_TOKEN_FILE) then
			fp = io.open(CLOUD_HOMECARE_TOKEN_FILE, "r")
			token = fp:read("*line")
			origin_url = fp:read("*line") .. url_postfix
			fp:close()
		else		
			break
		end
	end
	
	local data
	if nixio.fs.access("/tmp/cloud/cloud_report_app_dpi") then
		fp = io.open("/tmp/cloud/cloud_report_app_dpi", "r")
		data = fp:read("*all")
		fp:close()
	end

	if data == nil then
		break
	end
	
	sys.call("echo `date` >/var/log/cloud_report_app_dpi.result; echo '%s' >>/var/log/cloud_report_app_dpi.result" % {data})
	--dbg.print("cloud_upload request:", data)
	
	local ret
	fp = io.popen("curl --tlsv1.2 -S -l -H \"%s\" -H \"Authorization: %s\" -X POST -d \'%s\' --cacert %s --connect-timeout 8 %s --retry 3 --retry-delay 1 2>>/var/log/cloud_report_app_dpi.result" % {content_type, token, data, CACERT_FILE, origin_url})
	if fp then
		ret = fp:read("*all")
		fp:close()
	end

	dbg.print("cloud_upload dpi, response:",ret)
	ret = json.decode(ret)

	if ret ~= nil then
		if tonumber(ret.code) == error.ERROR_MSG.ERROR_INVALID_DEVICE_TOKEN[1] then
			--refresh token and upload again
			sys.call("rm " .. CLOUD_HOMECARE_TOKEN_FILE)
			retry = true
		end
	end
	
	if retry == false then
		break
	end
	
end