#!/bin/sh

. /lib/functions.sh

[ "$ACTION" == "ifup" ] && [ "$INTERFACE" == "wan" -o "$INTERFACE" == "lan" -o "$INTERFACE" == "internet" ] && {
    /etc/init.d/guestnetwork_bandwidth_ctrl restart
}

