#!/bin/sh /etc/rc.common

START=81

local found_url_cat=0

accel_support_enable() {	
	echo "enter accel_support_enable()">/dev/console
	
	#disable L3 accelerator
#	[ -e /sys/kernel/debug/ecm/ ] && {
#		echo 0 > /sys/kernel/debug/ecm/ecm_nss_ipv4/register_L3_hook
#		echo 0 > /sys/kernel/debug/ecm/ecm_nss_ipv6/register_L3_hook
#	}
}

accel_support_disable() {	
	echo "enter accel_support_disable()">/dev/console
	
	#enable L3 accelerator
#	[ -e /sys/kernel/debug/ecm/ ] && {
#		echo 1 > /sys/kernel/debug/ecm/ecm_nss_ipv4/register_L3_hook
#		echo 1 > /sys/kernel/debug/ecm/ecm_nss_ipv6/register_L3_hook
#	}
}

check_url_class()
{
	config_get filter_categories_list $1 filter_categories_list "0"
	config_get available $1 available "false"
	echo "filter_categories_list: $filter_categories_list" >/dev/console
	echo "available: $available" >/dev/console
	
	if [ -n "$available" -a "$available" == "true" ];then
		if [ -n "$filter_categories_list" -a "$filter_categories_list" != "0" ];then
			found_url_cat=1
			echo "found_url_cat: $found_url_cat" >/dev/console
		fi
	fi
}

should_load_avira_kctl() {
	local mode=$(uci get sysmode.sysmode.mode)
	local bind_status=$(uci get cloud_config.device_status.bind_status)
	if [ "x$mode" != "xrouter" -o "x$bind_status" != "x1" ]; then
		echo "0"
		return
	fi

	local wan_type=$(uci get network.wan.wan_type)
	if [ "x$wan_type" == "xv6plus" -o "x$wan_type" == "xdslite" ];then
		echo "here...x$wan_type" >/dev/console
		echo "0"
		return
	fi

	local qos_enable=$(uci get qos_v2.settings.enable)
	if [ "x$qos_enable" == "xon" ];then
		echo "here...qos is enabled" >/dev/console
		echo "1"
		return
	fi

    local state=`uci -q get avira.info.state`
    if [ "x$state" == "xpaid" ];then
		echo "here...x$state" >/dev/console
        echo "1"
		return
	fi

	found_url_cat=0	
	config_load parental_control_v2
	config_foreach check_url_class owner

	if [ "$found_url_cat" == "1" ]; then
		echo "here...found_url_cat" >/dev/console
		echo "1"
		return
	fi
	
	echo "not enable" >/dev/console
	echo "0"
	return
}

# start and restart will test if it need to be started
start() {
	local ret=$(should_load_avira_kctl)
	if [ "x$ret" == "x1" ]; then
		accel_support_enable
	else
		accel_support_disable
	fi
}

#stop means force stop
stop() {
	accel_support_disable
}

# start and restart will test if it need to be started
restart() {
	start
}