#!/bin/sh /etc/rc.common
# Copyright(c) 2008-2014 Shenzhen TP-LINK Technologies Co.Ltd.
#
# Details : The init script for logd.
# Author  : Ye Qianchuan <yeqianchuan@tp-link.net>
# Version : 1.0
# Date    : 17 Jul, 2014

SERVICE_DAEMONIZE=1

boot() {
    return 0
}

start() {
    config_load system
    local args log_size flash_safe_log_size
    config_get log_size system log_size 128
    config_get conf_log_size system conf_log_size 1
    args="-C ${log_size} -S ${conf_log_size}"
    
    service_start /usr/sbin/logd -k $args
    [ -f "/usr/sbin/nm_conf_log_init" ] && /usr/sbin/nm_conf_log_init
}

stop() {
    service_stop /usr/sbin/logd
    [ -f "/usr/sbin/nm_conf_log_exit" ] && /usr/sbin/nm_conf_log_exit
}
