#!/bin/sh /etc/rc.common
# Copyright (C) 2008-2010 OpenWrt.org

START=99

PC_LIBDIR=/lib/qos

gaming_lan_support=$(uci get profile.@qos_v2[0].gaming_lan_support -c /etc/profile.d/ -q)
qos_enable=$(uci get qos_v2.settings.enable|grep on)
[ "$gaming_lan_support" = "yes" ] && . /lib/gaming-lan-ctrl/gaming_lan.sh

pc() {
	. $PC_LIBDIR/core.sh
	local func=$1
	shift
	fw_$func $@
}

start() {
	local sysmode=$(uci get sysmode.sysmode.mode)
	if [ "${sysmode}" != "router" ]; then
		return 0
	fi
	
	if [ ! -f /etc/config/qos_v2 ];then
		touch /etc/config/qos_v2
		uci set qos_v2.settings='global'
		uci set qos_v2.settings.enable='off'
		uci set qos_v2.settings.up_band='1000'
		uci set qos_v2.settings.down_band='1000'
		uci set qos_v2.settings.up_unit='mbps'
		uci set qos_v2.settings.down_unit='mbps'
		uci set qos_v2.settings.high='90'
		uci set qos_v2.settings.low='10'
		uci commit
	fi
        [ "$gaming_lan_support" = "yes" ] && {
        	kgaming_lan_mod_insert
                	
        }
	pc start
	
}

stop() {
	[ "$gaming_lan_support" = "yes" ] && kgaming_lan_mod_remove
	pc stop $@
}

restart() {
	if [ "$gaming_lan_support" = "yes" ]; then
		local kgaming_module=$(lsmod |grep kgaming_lan)
		if [ "$qos_enable" = "on" ]; then
			[ -z "$kgaming_module" ] && kgaming_lan_mod_insert
		else
			[ -n "$kgaming_module" ] && kgaming_lan_mod_remove
		fi
	fi
	pc restart
}

reload() {
	pc reload
}
