#!/bin/sh
. /lib/functions.sh

CONFIG_PCTL="parental_control_v2"
need_commit=0

resetBonusTime()
{
	local section="$1"
	local bonusTime
	local rewardsTime
	local ign_online
	local ign_website

	config_get bonusTime "$section" today_bonus_time
	echo "##$bonusTime##$CONFIG_PCTL##$section"
	if [ -n "$bonusTime" -a x"$bonusTime" != x"0" ]; then
		uci set "$CONFIG_PCTL.$section.yesterday_bonus_time"=$bonusTime
		uci set "$CONFIG_PCTL.$section.today_bonus_time"='0'
		need_commit=2
	fi

	config_get rewardsTime "$section" today_reward_time
	if [ -n "$rewardsTime" -a x"$rewardsTime" != x"0" ]; then
		uci set "$CONFIG_PCTL.$section.yesterday_reward_time"=$rewardsTime
		uci set "$CONFIG_PCTL.$section.today_reward_time"='0'
		need_commit=2
	fi

	#### Reset Ignore online/website request!!! ####
	config_get ign_online "$section" ign_online
	echo "##$ign_online##$CONFIG_PCTL##$section"
	if [ -n "$ign_online" -a x"$ign_online" != x"0" ]; then
		uci set "$CONFIG_PCTL.$section.ign_online"='0'
		need_commit=1
	fi

	config_get ign_website "$section" ign_website
	echo "##$ign_website##$CONFIG_PCTL##$section"
	if [ -n "$ign_website" -a x"$ign_website" != x"0" ]; then
		uci set "$CONFIG_PCTL.$section.ign_website"='0'
		need_commit=1
	fi
	#### Reset Ignore online/website request!!! ####

	config_get cross_day "$section" cross_day "false"
	config_get bonus_end "$section" bonus_end
	if [ -n "$bonus_end" -a x"$bonus_end" != x"0" ];then
		if [ "$cross_day" == "true" ];then
			uci set "$CONFIG_PCTL.$section.today_bonus_time"=$bonus_end
			uci set "$CONFIG_PCTL.$section.cross_day"='false'
		else
			uci set "$CONFIG_PCTL.$section.bonus_end"='0'
		fi
		need_commit=2
	fi
}

config_load $CONFIG_PCTL
config_foreach resetBonusTime owner
config_clear
if [ "$need_commit" -gt 0 ]; then
	#### writeback to /etc/config/parental_control_v2
	uci commit
	uci_commit_flash
	if [ "$need_commit" -eq 2 ]; then
		/etc/init.d/parental_control reload
	fi
fi
