#!/bin/sh /etc/rc.common
# Copyright (C) 2008-2010 OpenWrt.org

START=97

PC_LIBDIR=/lib/client_speed_limit


client_speed_limit() {
	. $PC_LIBDIR/csl_core.sh
	csl_$1
}

start() {
	local sysmode=$(uci get sysmode.sysmode.mode)
	if [ "${sysmode}" != "router" ]; then
		return 0
	fi

	if [ ! -f /etc/config/client_speed_limit ];then
		touch /etc/config/client_speed_limit
		uci commit
	fi
	client_speed_limit start
}

stop() {
	client_speed_limit stop
}

restart() {
	client_speed_limit restart
}

reload() {
	client_speed_limit reload
}

