#!/bin/sh /etc/rc.common
# Copyright (C) 2008-2010 OpenWrt.org

START=99

PC_LIBDIR=/lib/guestnetwork_effectivetime_ctrl

guestnetwork_effectivetime_ctrl() {
	. $PC_LIBDIR/core.sh
	gec_$1
}

start() {
	guestnetwork_effectivetime_ctrl start
}

stop() {
	guestnetwork_effectivetime_ctrl stop
}

restart() {
	guestnetwork_effectivetime_ctrl restart
}

