#!/bin/sh /etc/rc.common
# Copyright (C) 2008-2010 OpenWrt.org

START=48

regenMeshkey() {
    local needRegen=$(uci get profile.@onemesh[0].key_regenerate -c "/etc/profile.d/" -q)
    if [ "$needRegen" == "true" ]; then
        luarsa_keys_gen 1024 meshkeys
    fi
}

start() {
    #if [ ! -e usr/bin/openssl ]; then
    local rsa2048_enable=$(uci get system.system.rsa2048_enable)
    if [ "$rsa2048_enable" == "true" ]; then
        luarsa_keys_gen 2048
    fi
    #fi
    regenMeshkey
}

restart() {
    #if [ ! -e usr/bin/openssl ]; then
    local rsa2048_enable=$(uci get system.system.rsa2048_enable)
    if [ "$rsa2048_enable" == "true" ]; then
        luarsa_keys_gen 2048
    fi
    #fi
    regenMeshkey
}

reload() {
    #if [ ! -e usr/bin/openssl ]; then  
    local rsa2048_enable=$(uci get system.system.rsa2048_enable)
    if [ "$rsa2048_enable" == "true" ]; then
        luarsa_keys_gen 2048
    fi
    #fi
    regenMeshkey
}
