#!/usr/bin/lua
--created by wanghao

local error = require "cloud_report.report_error"
local sys   = require "luci.sys"
local nixio = require "nixio"
local dbg   = require "luci.tools.debug"
local json = require "luci.json"
local io    = require "io"
local uci			= require "luci.model.uci"
local uci_r			= uci.cursor()

local content_type = "Content-type: application/json"
local url_postfix = "/v1/license"
local CLOUD_HOMECARE_TOKEN_FILE = "/tmp/cloud/cloud_token_homecare"
local CLOUD_SERVER_URL = "n-devs-gw.tplinkcloud.com"

local CLOUD_REPORT_MOD_ID = 231
local REPORT_UNBIND_SUCCESS = 52
local REPORT_UNBIND_FAILED = 202
local logm    = require "luci.model.log"
local log  = logm.Log(CLOUD_REPORT_MOD_ID)

local retry_count = 0
local token
local origin_url
local fp
local retry = false

-- online test
while true
do
	is_offline = sys.fork_call("dnslookup '%s'" % {CLOUD_SERVER_URL} )
	if is_offline == 0 then
		break
	else
		nixio.nanosleep(5, 0)
	end
end

-- set "hardware = no" whether license is success or not
uci_r:set("avira", "info", "hardware", "no")
uci_r:commit("avira")

while true
do
	retry = false

	if not nixio.fs.access(CLOUD_HOMECARE_TOKEN_FILE) then
		sys.call("cloud_getDevToken homecare")
	end

	if nixio.fs.access(CLOUD_HOMECARE_TOKEN_FILE) then
		fp = io.open(CLOUD_HOMECARE_TOKEN_FILE, "r")
		token = fp:read("*line")
		origin_url = fp:read("*line")..url_postfix
		fp:close()
	else
		-- try again when not get the homecare token
		sys.call("cloud_getDevToken homecare")
		if nixio.fs.access(CLOUD_HOMECARE_TOKEN_FILE) then
			fp = io.open(CLOUD_HOMECARE_TOKEN_FILE, "r")
			token = fp:read("*line")
			origin_url = fp:read("*line") .. url_postfix
			fp:close()
		else
			break
		end
	end
	
	local account = uci_r:get("cloud_config","device_status", "accountid") or arg[1]
	local data = {
		["deviceId"] = string.match(sys.exec("getfirm DEV_ID"), "%w+"),
		["accountId"] = account
	}

	sys.call("echo `date` >/var/log/cloud_report_unbind.result; echo '%s' >>/var/log/cloud_report_unbind.result" % {json.encode(data)})
	dbg.print("[cloud-report][" .. arg[0] .. "][cloud_upload request]:", json.encode(data))

	local ret
	fp = io.popen("curl --tlsv1.2 -S -l -H \"%s\" -H \"Authorization: %s\" -X DELETE -k -d \'%s\' --connect-timeout 8 %s --retry 3 --retry-delay 1 2>>/var/log/cloud_report_unbind.result" % {content_type, token, json.encode(data), origin_url})
	if fp then
		ret = fp:read("*all")
		fp:close()
	end

	dbg.print("[cloud-report][" .. arg[0] .. "][cloud_upload response]:", ret)

	ret = json.decode(ret)

	-- ERROR_MSG:  /usr/lib/lua/cloud_report/report_error.lua
	if ret ~= nil then
		log(REPORT_UNBIND_FAILED, ret.code)
		if tonumber(ret.code) == error.ERROR_MSG.ERROR_INVALID_DEVICE_TOKEN[1] then
			--refresh token and upload again
			sys.call("rm " .. CLOUD_HOMECARE_TOKEN_FILE)
		elseif tonumber(ret.code) == error.ERROR_MSG.ERROR_NO_DATA[1] then
			dbg.print("[cloud-report][" .. arg[0] .. "]: No paid license")
			return false
		end
		if retry_count >= 10 then
			nixio.nanosleep(86400, 0)
		else
			nixio.nanosleep(60, 0)
		end
	else
		log(REPORT_UNBIND_SUCCESS)
		return true
	end
	
	if retry == false then
		break
	end

	retry_count = retry_count + 1
end
