#!/bin/sh

#wait 20mins to backup rootfs in double image patter
sleep 1200

echo "Backup rootfs check begin......" >/dev/console 2>&1
nvrammanager -b
result=`nvram get image_copy`
echo "Backup rootfs check end[image_copy $result]......" >/dev/console 2>&1

